In [3]:
import cv2
import os
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('../HomeWorks/-XiMQJ9rNfY1.jpg')
scale_up_x = 0.5
scale_up_y = 0.5
scale_down = 0.6
width = int(img.shape[1] * scale_up_x)
height = int(img.shape[0] * scale_up_y)
dim = (width, height)
a = res_inter_nearset = cv2.resize(img, dim, interpolation = cv2.INTER_NEAREST)
b = res_inter_linear = cv2.resize(img, dim, interpolation = cv2.INTER_LINEAR)
c = res_inter_area = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
print(a)
print(b)
print(c)

cv2.imshow('INTER_NEARES',a)
cv2.waitKey()

cv2.imshow('INTER_LINEAR',b)
cv2.waitKey()

cv2.imshow('INTER_AREA',c)
cv2.waitKey()
cv2.destroyAllWindows()

[[[ 49   1   0]
  [ 49   1   0]
  [ 49   1   0]
  ...
  [ 36   0   6]
  [ 33   0   5]
  [ 32   0   3]]

 [[ 50   0   0]
  [ 50   0   0]
  [ 50   0   0]
  ...
  [ 36   0   6]
  [ 34   0   6]
  [ 34   0   6]]

 [[ 50   0   0]
  [ 50   0   0]
  [ 50   0   0]
  ...
  [ 36   0   6]
  [ 36   0   6]
  [ 35   0   5]]

 ...

 [[  8  31  27]
  [ 45  78  71]
  [  5  22  19]
  ...
  [  7 152 174]
  [  0  69  86]
  [ 24 109 105]]

 [[  1  14   6]
  [  0   6   0]
  [ 72 137 145]
  ...
  [  1 128 159]
  [  0 101 127]
  [  1  82  90]]

 [[  1   0   7]
  [144 236 241]
  [ 86 225 234]
  ...
  [  3  11  40]
  [  1 108 136]
  [  0  35  40]]]
[[[ 49   1   0]
  [ 49   1   0]
  [ 49   1   0]
  ...
  [ 35   0   6]
  [ 33   0   5]
  [ 33   1   4]]

 [[ 50   0   0]
  [ 50   0   0]
  [ 50   0   0]
  ...
  [ 35   0   6]
  [ 33   0   5]
  [ 34   0   5]]

 [[ 50   0   0]
  [ 50   0   0]
  [ 50   0   0]
  ...
  [ 36   0   6]
  [ 37   1   6]
  [ 37   0   6]]

 ...

 [[  2  16  12]
  [  0  15  10]
  [ 21  46  52]
  ..

In [4]:
# divide into patches

size = img.shape
print(size)

columns = 3
rows = 3

y_patch_length = size[0] / 3
x_patch_length = size[1] / 3
for i in range(0, rows):
    for j in range(0, columns):
        int_x_patch = int(x_patch_length)
        int_y_patch = int(y_patch_length)
        cropped_x = int_x_patch * j
        cropped_x1 = int_x_patch * (j+1)
        cropped_y = int_y_patch * i
        cropped_y1 = int_y_patch * (i+1)
        patch = img[cropped_y : cropped_y1, cropped_x : cropped_x1]
        cv2.imwrite('../HomeWorks/patch('+ str(i) +':'+ str(j) + '.png', patch)

(1365, 2048, 3)


In [5]:
#display patches
import matplotlib.pyplot as plt

fig1, fig2 = plt.subplots(nrows=rows, ncols=columns)
for i in range(0, rows):
    for j in range(0, columns):
        img = plt.imread('../HomeWorks/patch('+ str(i) +':'+ str(j) + '.png')
        fig2[i,j].axis('off')
        fig2[i,j].imshow(img)
plt.tight_layout()
plt.show()